const obj = {
    title: 'PSM',
    description: '코코아 파이낸스 PSM',
    address: '0xC9880f5809964924373b65a3f77e64cB0fb583C4',
    abi: `[{
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "address",
            "name": "previousAdmin",
            "type": "address"
        }, {
            "indexed": false,
            "internalType": "address",
            "name": "newAdmin",
            "type": "address"
        }],
        "name": "AdminChanged",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": true,
            "internalType": "address",
            "name": "beacon",
            "type": "address"
        }],
        "name": "BeaconUpgraded",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": true,
            "internalType": "address",
            "name": "implementation",
            "type": "address"
        }],
        "name": "Upgraded",
        "type": "event"
    }, {
        "stateMutability": "payable",
        "type": "fallback"
    }, {
        "inputs": [],
        "name": "admin",
        "outputs": [{
            "internalType": "address",
            "name": "admin_",
            "type": "address"
        }],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "newAdmin",
            "type": "address"
        }],
        "name": "changeAdmin",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [],
        "name": "implementation",
        "outputs": [{
            "internalType": "address",
            "name": "implementation_",
            "type": "address"
        }],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "newImplementation",
            "type": "address"
        }],
        "name": "upgradeTo",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "newImplementation",
            "type": "address"
        }, {
            "internalType": "bytes",
            "name": "data",
            "type": "bytes"
        }],
        "name": "upgradeToAndCall",
        "outputs": [],
        "stateMutability": "payable",
        "type": "function"
    }, {
        "stateMutability": "payable",
        "type": "receive"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "uint256",
            "name": "inAmount",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "uint256",
            "name": "outAmount",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "address",
            "name": "inToken",
            "type": "address"
        }, {
            "indexed": false,
            "internalType": "address",
            "name": "outToken",
            "type": "address"
        }],
        "name": "ActiveExchange",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "address",
            "name": "token",
            "type": "address"
        }],
        "name": "LogAddToken",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "address",
            "name": "token",
            "type": "address"
        }],
        "name": "LogRemoveToken",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "uint256",
            "name": "inAmount",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "uint256",
            "name": "outAmount",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "address",
            "name": "inToken",
            "type": "address"
        }, {
            "indexed": false,
            "internalType": "address",
            "name": "outToken",
            "type": "address"
        }],
        "name": "PassiveExchange",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "address",
            "name": "account",
            "type": "address"
        }],
        "name": "Paused",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": true,
            "internalType": "bytes32",
            "name": "role",
            "type": "bytes32"
        }, {
            "indexed": true,
            "internalType": "bytes32",
            "name": "previousAdminRole",
            "type": "bytes32"
        }, {
            "indexed": true,
            "internalType": "bytes32",
            "name": "newAdminRole",
            "type": "bytes32"
        }],
        "name": "RoleAdminChanged",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": true,
            "internalType": "bytes32",
            "name": "role",
            "type": "bytes32"
        }, {
            "indexed": true,
            "internalType": "address",
            "name": "account",
            "type": "address"
        }, {
            "indexed": true,
            "internalType": "address",
            "name": "sender",
            "type": "address"
        }],
        "name": "RoleGranted",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": true,
            "internalType": "bytes32",
            "name": "role",
            "type": "bytes32"
        }, {
            "indexed": true,
            "internalType": "address",
            "name": "account",
            "type": "address"
        }, {
            "indexed": true,
            "internalType": "address",
            "name": "sender",
            "type": "address"
        }],
        "name": "RoleRevoked",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "address",
            "name": "token",
            "type": "address"
        }],
        "name": "StakeToManager",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "address",
            "name": "token",
            "type": "address"
        }],
        "name": "StakeToken",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "address",
            "name": "account",
            "type": "address"
        }],
        "name": "Unpaused",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "address",
            "name": "token",
            "type": "address"
        }],
        "name": "UnstakeFromManager",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "address",
            "name": "token",
            "type": "address"
        }],
        "name": "UnstakeToken",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "address",
            "name": "token",
            "type": "address"
        }, {
            "indexed": false,
            "internalType": "address",
            "name": "to",
            "type": "address"
        }],
        "name": "WithdrawToken",
        "type": "event"
    }, {
        "inputs": [],
        "name": "DEFAULT_ADMIN_ROLE",
        "outputs": [{
            "internalType": "bytes32",
            "name": "",
            "type": "bytes32"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "PSM_ASSET_MANAGER",
        "outputs": [{
            "internalType": "contract IPSMAssetManager",
            "name": "",
            "type": "address"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "uint256",
            "name": "passiveExchangeFee_",
            "type": "uint256"
        }, {
            "internalType": "uint256",
            "name": "activeExchangeThreshold_",
            "type": "uint256"
        }],
        "name": "__PSM_init",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "_token",
            "type": "address"
        }, {
            "internalType": "uint256",
            "name": "inAmount",
            "type": "uint256"
        }, {
            "internalType": "uint256",
            "name": "minOutAmount",
            "type": "uint256"
        }],
        "name": "activeExchange",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [],
        "name": "activeExchangeThreshold",
        "outputs": [{
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "_token",
            "type": "address"
        }],
        "name": "addToken",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "bytes32",
            "name": "what",
            "type": "bytes32"
        }, {
            "internalType": "uint256",
            "name": "data",
            "type": "uint256"
        }],
        "name": "config",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "",
            "type": "address"
        }],
        "name": "debtBalance",
        "outputs": [{
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "_token",
            "type": "address"
        }, {
            "internalType": "uint256",
            "name": "inAmount",
            "type": "uint256"
        }],
        "name": "estimateActiveExchange",
        "outputs": [{
            "internalType": "uint256",
            "name": "swapOutAmount",
            "type": "uint256"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "uint256",
            "name": "inAmount",
            "type": "uint256"
        }, {
            "internalType": "address",
            "name": "inToken",
            "type": "address"
        }, {
            "internalType": "address",
            "name": "outToken",
            "type": "address"
        }],
        "name": "estimatePassiveExchange",
        "outputs": [{
            "internalType": "uint256",
            "name": "outAmount",
            "type": "uint256"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "_token",
            "type": "address"
        }],
        "name": "getActiveStatus",
        "outputs": [{
            "internalType": "uint256",
            "name": "status",
            "type": "uint256"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "_token",
            "type": "address"
        }],
        "name": "getPrice",
        "outputs": [{
            "internalType": "uint256",
            "name": "tokenPrice",
            "type": "uint256"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "bytes32",
            "name": "role",
            "type": "bytes32"
        }],
        "name": "getRoleAdmin",
        "outputs": [{
            "internalType": "bytes32",
            "name": "",
            "type": "bytes32"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "_token",
            "type": "address"
        }],
        "name": "getTokenBalance",
        "outputs": [{
            "internalType": "uint256",
            "name": "tokenBalance",
            "type": "uint256"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "bytes32",
            "name": "role",
            "type": "bytes32"
        }, {
            "internalType": "address",
            "name": "account",
            "type": "address"
        }],
        "name": "grantRole",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "bytes32",
            "name": "role",
            "type": "bytes32"
        }, {
            "internalType": "address",
            "name": "account",
            "type": "address"
        }],
        "name": "hasRole",
        "outputs": [{
            "internalType": "bool",
            "name": "",
            "type": "bool"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "_token",
            "type": "address"
        }],
        "name": "isValidToken",
        "outputs": [{
            "internalType": "bool",
            "name": "valid",
            "type": "bool"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "nakedKSD",
        "outputs": [{
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "uint256",
            "name": "inAmount",
            "type": "uint256"
        }, {
            "internalType": "address",
            "name": "inToken",
            "type": "address"
        }, {
            "internalType": "address",
            "name": "outToken",
            "type": "address"
        }],
        "name": "passiveExchange",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [],
        "name": "passiveExchangeFee",
        "outputs": [{
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "pause",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [],
        "name": "paused",
        "outputs": [{
            "internalType": "bool",
            "name": "",
            "type": "bool"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "_token",
            "type": "address"
        }],
        "name": "removeToken",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "bytes32",
            "name": "role",
            "type": "bytes32"
        }, {
            "internalType": "address",
            "name": "account",
            "type": "address"
        }],
        "name": "renounceRole",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "bytes32",
            "name": "role",
            "type": "bytes32"
        }, {
            "internalType": "address",
            "name": "account",
            "type": "address"
        }],
        "name": "revokeRole",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
        }, {
            "internalType": "address",
            "name": "_token",
            "type": "address"
        }],
        "name": "stakeToken",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "uint256",
            "name": "i",
            "type": "uint256"
        }],
        "name": "token",
        "outputs": [{
            "internalType": "address",
            "name": "",
            "type": "address"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "",
            "type": "address"
        }],
        "desc": "PSM 유보 스테이블코인 잔고",
        "name": "tokenBalance",
        "outputs": [{
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "tokenLength",
        "outputs": [{
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [],
        "name": "tokenList",
        "desc": "PSM 유보 스테이블코인 토큰주소 리스트",
        "outputs": [{
            "internalType": "address[]",
            "name": "",
            "type": "address[]"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "newOwner",
            "type": "address"
        }],
        "name": "transferOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [],
        "name": "unpause",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
        }, {
            "internalType": "address",
            "name": "_token",
            "type": "address"
        }],
        "name": "unstakeToken",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
        }, {
            "internalType": "address",
            "name": "_token",
            "type": "address"
        }, {
            "internalType": "address",
            "name": "to",
            "type": "address"
        }],
        "name": "withdrawToken",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "address",
            "name": "_logic",
            "type": "address"
        }, {
            "internalType": "address",
            "name": "admin_",
            "type": "address"
        }, {
            "internalType": "bytes",
            "name": "_data",
            "type": "bytes"
        }],
        "stateMutability": "payable",
        "type": "constructor"
    }]
`}
export default obj;
